# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: Default

steps:

- script: |
    java -version
  env:
    JAVA_HOME: $(JAVA_HOME_8_X64)
    PATH: $(JAVA_HOME_8_X64)/bin:$(PATH)

- script: sourceanalyzer -v
- task: FortifySCA@7
  inputs:
    licenseFile: 'C:\fortify.license'
    applicationType: 'other'
    buildAnalyzerParams: 'mvn com.fortify.sca.plugins.maven:sca-maven-plugin:translate'
    fortifySourceTranslate: 'pom.xml'
    fortifyBuildId: 'ahmet2'
    scaVerbose: true
    scaDebug: true
    fortifyScanType: 'LocalScan'